# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeometryUpdater
                                 A QGIS plugin
 replace Geometry
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-15
        copyright            : (C) 2024 by Federico Gianoli
        email                : gianoli.federico@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Federico Gianoli'
__date__ = '2024-12-15'
__copyright__ = '(C) 2024 by Federico Gianoli'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeometryUpdater class from file GeometryUpdater.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GeometryUpdater import GeometryUpdaterPlugin
    return GeometryUpdaterPlugin()
